name: Actions标题
run-name: ${{ github.actor }} 正在测试GitHub Actions 🚀
on:
  push:
    branches:
      - 'master'
jobs:
  TestGithubAction:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 该任务通过${{ github.event_name }}事件自动触发。"
      - run: echo "🐧 该任务正在由GitHub托管的${{ runner.os }}服务器上运行。"
      - run: echo "🔎 当前分支是${{ github.ref }}，仓库地址是${{ github.repository }}。"
      - name: 拉取仓库代码
        uses: actions/checkout@v4
      - run: echo "💡 ${{ github.repository }}仓库已经成功拉取到该runner。"
      - run: echo "🖥️ 该工作流已经准备好测试您的代码了。"
      - name: 列出仓库的文件
        run: |
          ls -al ${{ github.workspace }}
      - run: echo "🍏 该任务当前状态是${{ job.status }}。"
