name: 打包部署到gh-pages
on: push
jobs:
  RunTesting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: 拉取代码
      - run: |
          npm ci
          npm run build
          pwd
          ls -al
